
[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "duckrun"
version = "0.1.1"
description = "Lakehouse task runner powered by DuckDB for Microsoft Fabric"
readme = "README.md"
license = "MIT"
requires-python = ">=3.9"

[project.urls]
Homepage = "https://github.com/djouallah/duckrun"
Repository = "https://github.com/djouallah/duckrun"
Issues = "https://github.com/djouallah/duckrun/issues"

