"""Run the aemo dbt build + test on Fabric compute in ONE throwaway notebook (RemoteRunner).

The real end-to-end exercise of duckrun's remote executor: instead of running dbt on the runner,
ship ONLY the aemo dbt logic (models + macros + scrubbed profiles.yml) into a single temporary
Fabric notebook at cores=8, run `dbt build` then `dbt test` there, and delete the notebook. Both
commands run in the SAME notebook (one Fabric session, one pip install) via RemoteRunner's batched
`with` form. External assets (dim_calendar, the AEMO CSVs) are NOT embedded — they live in OneLake
and are read via source(); the calendar is generated by scripts/generate_calendar.py first.

The whole point of going remote is Fabric compute, so the data volume (download_limit / process_limit)
is turned up well past what the local aemo runner uses — see .github/workflows/aemo_remote.yml.

RemoteRunner auto-forwards the project's non-secret env_var config (WAREHOUSE_PATH, FILES_PATH,
DBT_SCHEMA, download_limit, process_limit) into the notebook and deliberately drops ONELAKE_TOKEN —
inside Fabric the storage token comes from notebookutils.

Run from the aemo project dir, after `az login`, with FABRIC_TOKEN + ONELAKE_TOKEN set (see
.github/workflows/aemo_remote.yml). Exits non-zero if build or test fails.
"""
import os
import sys

from duckrun import RemoteRunner


def main() -> int:
    runner = RemoteRunner(
        cores=8,
        target="dev",
        # Normal released duckrun from PyPI in the notebook — the thing under test is RemoteRunner's
        # orchestration (create/run/delete), which runs here on the runner.
        pip_spec="duckrun",
        # Control plane vs storage: distinct scopes, minted separately in CI.
        fabric_token=os.environ["FABRIC_TOKEN"],
        storage_token=os.environ["ONELAKE_TOKEN"],
    )

    # Batched: build then test run in ONE notebook (one session start, one install).
    with runner as dbt:
        build = dbt.invoke(["build", "--target", "dev", "--exclude", "tag:heavy"])
        test = dbt.invoke(["test", "--target", "dev", "--exclude", "tag:heavy"])
    # results are populated after the block exits (the notebook has run + been deleted)

    ok = True
    for label, res in (("build", build), ("test", test)):
        print(f"\n=== remote `dbt {label}` -> success={res.success} ===")
        for node in res.result or []:
            print(f"  {node.get('node')}: {node.get('status')}")
        ok = ok and bool(res.success)

    print(f"\nRemote build + test {'PASSED' if ok else 'FAILED'}.")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
