"""Build the aemo dbt project on Fabric compute via a throwaway notebook (RemoteRunner).

The real end-to-end exercise of duckrun's remote executor: instead of running `dbt build` on the
runner, this ships ONLY the aemo dbt logic (models + macros + scrubbed profiles.yml) into a
temporary Fabric notebook at cores=8, runs `dbt build` there, and deletes the notebook. External
assets (dim_calendar, the AEMO CSVs) are NOT embedded — they live in OneLake and are read via
source(); the calendar is generated by scripts/generate_calendar.py in a separate step first.

RemoteRunner auto-forwards the project's non-secret env_var config (WAREHOUSE_PATH, FILES_PATH,
DBT_SCHEMA, download_limit, process_limit) into the notebook and deliberately drops ONELAKE_TOKEN —
inside Fabric the storage token comes from notebookutils.

Run from the aemo project dir, after `az login`, with FABRIC_TOKEN + ONELAKE_TOKEN set (see
.github/workflows/aemo_remote.yml). Exits non-zero if the remote dbt build fails.
"""
import os
import sys

from duckrun import RemoteRunner


def main() -> int:
    # Install THIS commit's duckrun in the notebook so the run tests the branch, not the last release.
    sha = os.environ.get("GITHUB_SHA", "main")
    pip_spec = f"git+https://github.com/djouallah/duckrun@{sha}"

    runner = RemoteRunner(
        cores=8,
        target="dev",
        pip_spec=pip_spec,
        # Control plane vs storage: distinct scopes, minted separately in CI.
        fabric_token=os.environ["FABRIC_TOKEN"],
        storage_token=os.environ["ONELAKE_TOKEN"],
    )

    # Mirror the local aemo CI: full build, skipping the heavy fct_summary validations.
    res = runner.invoke(["build", "--target", "dev", "--exclude", "tag:heavy"])

    print(f"remote dbt build success={res.success}")
    for node in res.result or []:
        print(f"  {node.get('node')}: {node.get('status')}")
    return 0 if res.success else 1


if __name__ == "__main__":
    sys.exit(main())
