"""Run the aemo dbt build + test, choosing local vs Fabric-remote by how much work is pending.

A pre-flight counts the real MART backlog — archive-log files not yet folded into the fact tables
(fct_scada / fct_price): what's in ``csv_archive_log.parquet`` (OneLake Files) minus what's already
processed (the fact tables' ``daily_file`` / ``intraday_file`` columns), the exact predicate the
project's ``assert_all_*_processed_*`` tests and the incremental pre-hooks use. This is the true
"files to process" and it shrinks as builds catch up (a download-side count never would). Then:

  * **few pending** (a quick re-run after a small model/doc tweak — barely any new files) → run dbt
    **locally** in-process on the runner. No Fabric notebook spin-up (~2-3 min) for a trivial build.
  * **many pending** (a fresh lakehouse, a real backfill, or a long gap since the last run) → ship
    ONLY the dbt logic into a throwaway Fabric Python notebook via ``RemoteRunner`` and run it there
    on Fabric compute, co-located with the lakehouse.

Local vs remote is purely *which runner we construct* — the dbt commands are identical either way.
The cutoff is ``REMOTE_THRESHOLD`` (default 50). If the pre-flight can't run (network hiccup), we
fail safe to **remote** rather than risk OOMing the 2-core runner on a big local build.

Run from the aemo project dir with the OIDC identity in the env (AZURE_CLIENT_ID / AZURE_TENANT_ID);
duckrun self-acquires the OneLake and Fabric tokens it needs — nothing is pre-minted. External assets
(dim_calendar, the AEMO CSVs) live in OneLake and are read via source(); the calendar is generated by
scripts/generate_calendar.py first. Exits non-zero if build or test fails.
"""
import os
import sys

BUILD = ["build", "--target", "dev", "--exclude", "tag:heavy"]
TEST = ["test", "--target", "dev", "--exclude", "tag:heavy"]

# Size the remote Fabric SKU (RemoteRunner cores) to how much work THIS run will actually merge.
# The merge working set — and thus RAM pressure, spill volume, and wall-clock — scales with the
# number of files folded, which is min(process_limit, backlog): a big backlog capped by a small
# process_limit is still a small merge, and a backlog below process_limit folds entirely in one go.
# Bigger fold -> bigger SKU: more RAM keeps more of the merge in memory (DuckDB limit 0.3x RAM,
# delta_rs max_spill_size 0.6x RAM) and a bigger disk to spill onto, trading $ for wall-clock so a
# large fold doesn't grind for an hour. Validated points: 8 cores (~60 GiB RAM, ~275 GiB disk)
# folded 3000 files but took ~74 min (heavy spill); 64 cores (~497 GiB RAM, ~2 TiB disk) did 1000
# fast. Rough tiers, not a tuned optimum — "or something", but monotonic in the work.
_CORE_TIERS = ((250, 8), (1000, 16), (2500, 32))  # (files <= N -> cores); above the top tier -> _MAX_CORES
_MAX_CORES = 64


def cores_for(files: int) -> int:
    """Remote SKU size for a run that will fold ``files`` source files into the marts."""
    for ceiling, cores in _CORE_TIERS:
        if files <= ceiling:
            return cores
    return _MAX_CORES

# Which fact table consumes which archive-log source, and the fact column that records the processed
# source file. 'daily' feeds BOTH facts; scada_today only fct_scada; price_today only fct_price;
# duid_* feed only dim_duid (full rebuild, no per-file backlog) so they're excluded. Marts land in
# schema 'landing' (dbt_project.yml +schema: landing).
_FACTS = {
    "fct_scada": ("landing/fct_scada", {"daily": "daily_file", "scada_today": "intraday_file"}),
    "fct_price": ("landing/fct_price", {"daily": "daily_file", "price_today": "intraday_file"}),
}


def count_pending() -> dict:
    """Per-(fact, source) MART backlog: archive-log files not yet folded into the fact table, using
    the exact predicate the assert tests / incremental pre-hooks use (log.csv_filename not present in
    the fact's daily_file/intraday_file). The real "files to process" — it shrinks as builds catch up.
    Returns {(fact, source_type): backlog_count}; {} when nothing has been downloaded yet."""
    import duckrun

    # WAREHOUSE_PATH accepts either OneLake spelling — the full abfss URL or the `<ws>/<item>`
    # shorthand — so expand before concatenating the fact sub-paths onto it. FILES_PATH stays a full
    # URL: sources.yml pastes it straight into read_csv_auto(), which never sees the expander.
    from dbt.adapters.duckrun.remote import expand_onelake_shorthand

    files_path = os.environ["FILES_PATH"].rstrip("/")
    warehouse_path = expand_onelake_shorthand(os.environ["WAREHOUSE_PATH"]).rstrip("/")
    # No token passed: for an abfss:// path duckrun.connect self-acquires the OneLake token itself
    # (GitHub OIDC / azure-identity). One read-only session (one OneLake azure secret) reads BOTH the
    # log parquet under Files and the fact Delta tables under Tables — sibling paths on the same account.
    conn = duckrun.connect(files_path, read_only=True)

    log_path = files_path + "/csv_archive_log.parquet"
    # Nothing downloaded yet -> nothing to process (routes local; the very first run is trivially small).
    if conn.sql(f"SELECT count(*) FROM glob('{log_path}')").fetchone()[0] == 0:
        return {}

    conn.sql(f"""
        CREATE OR REPLACE TEMP TABLE _log AS
        SELECT source_type, csv_filename
        FROM read_parquet('{log_path}')
        WHERE csv_filename IS NOT NULL
          AND source_type IN ('daily', 'scada_today', 'price_today')
    """)

    pending = {}
    for fact, (subpath, col_map) in _FACTS.items():
        delta_path = f"{warehouse_path}/{subpath}"
        try:
            # Scan the (large) fact ONCE: pull the tiny distinct processed-file set for both tracking
            # columns. daily_file/intraday_file are low-cardinality (one value per source file).
            conn.sql(f"""
                CREATE OR REPLACE TEMP TABLE _done AS
                SELECT DISTINCT 'daily_file'    AS col, daily_file    AS f
                FROM delta_scan('{delta_path}') WHERE daily_file    IS NOT NULL
                UNION
                SELECT DISTINCT 'intraday_file' AS col, intraday_file AS f
                FROM delta_scan('{delta_path}') WHERE intraday_file IS NOT NULL
            """)
            fresh = False
        except Exception:
            # Fresh lakehouse (no _delta_log yet) or a transport error: treat every log file for this
            # fact's sources as backlog (mirrors is_incremental()==False) — the safe over-count.
            fresh = True

        for source_type, fact_col in col_map.items():
            if fresh:
                (n,) = conn.sql(
                    f"SELECT count(*) FROM _log WHERE source_type = '{source_type}'"
                ).fetchone()
            else:
                # Null-safe anti-join = the assert_all_*_processed_* predicate exactly.
                (n,) = conn.sql(f"""
                    SELECT count(*) FROM _log l
                    WHERE l.source_type = '{source_type}'
                      AND NOT EXISTS (
                          SELECT 1 FROM _done d WHERE d.col = '{fact_col}' AND d.f = l.csv_filename
                      )
                """).fetchone()
            pending[(fact, source_type)] = n
    return pending


def _normalize(res):
    """(success, [(node, status), ...]) from either a dbtRunnerResult or a RemoteResult."""
    ok = bool(getattr(res, "success", False))
    nodes = []
    for r in getattr(res, "result", None) or []:
        if isinstance(r, dict):  # RemoteResult: list of {"node", "status"}
            nodes.append((r.get("node"), r.get("status")))
        else:  # dbtRunnerResult: list of RunResult
            node = getattr(getattr(r, "node", None), "name", None)
            nodes.append((node, str(getattr(r, "status", ""))))
    return ok, nodes


def run_local():
    from dbt.cli.main import dbtRunner

    dbt = dbtRunner()
    return _normalize(dbt.invoke(BUILD)), _normalize(dbt.invoke(TEST))


def run_remote(cores):
    from duckrun import RemoteRunner

    # Batched: build then test in ONE notebook (one session start, one install). This is a TEST, so
    # the notebook installs duckrun straight from THIS repo's main (not the released PyPI wheel) —
    # otherwise an adapter fix wouldn't be exercised remotely until the next release. ``cores`` is
    # sized to the fold size by cores_for() — more RAM raises DuckDB's merge memory_limit (0.3x RAM)
    # and delta_rs's max_spill_size (0.6x RAM), so less of a month-spanning merge spills to disk; the
    # old "100 GB" wall was delta_rs's max_temp_directory_size default, now sized to ~80% of free disk.
    # No tokens passed: RemoteRunner self-acquires the Fabric control-plane and OneLake tokens from the
    # OIDC identity (auth.get_fabric_token / get_onelake_token).
    with RemoteRunner(
        cores=cores,
        target="dev",
        pip_spec="git+https://github.com/djouallah/duckrun.git@main",
    ) as dbt:
        build = dbt.invoke(BUILD)
        test = dbt.invoke(TEST)
    return _normalize(build), _normalize(test)


def main() -> int:
    download_limit = int(os.environ.get("download_limit", "1000"))
    process_limit = int(os.environ.get("process_limit", "365"))
    threshold = int(os.environ.get("REMOTE_THRESHOLD", "50"))
    try:
        pending = count_pending()  # {(fact, source): unprocessed backlog}
        sc_daily = pending.get(("fct_scada", "daily"), 0)
        sc_today = pending.get(("fct_scada", "scada_today"), 0)
        pr_daily = pending.get(("fct_price", "daily"), 0)
        pr_today = pending.get(("fct_price", "price_today"), 0)
        # Distinct source files still to process — the user's "log minus processed". A daily file feeds
        # both facts and is folded in lockstep, so count it once (max of the two daily backlogs).
        backlog = max(sc_daily, pr_daily) + sc_today + pr_today
        remote = backlog > threshold
        # The merge this run actually folds is capped by process_limit; size the SKU to that.
        cores = cores_for(min(process_limit, backlog))
        print("[aemo] mart backlog — archive-log files not yet folded into the facts:", flush=True)
        print(f"[aemo]   fct_scada <- daily       : {sc_daily} unprocessed")
        print(f"[aemo]   fct_scada <- scada_today : {sc_today} unprocessed")
        print(f"[aemo]   fct_price <- daily       : {pr_daily} unprocessed")
        print(f"[aemo]   fct_price <- price_today : {pr_today} unprocessed")
        print(f"[aemo]   FILES TO PROCESS (distinct): {backlog}  "
              f"(each build folds up to {process_limit}/source; downloads up to {download_limit}/source; "
              f"remote cores={cores})")
        why = f"{backlog} to process {'>' if remote else '<='} threshold={threshold}"
    except Exception as exc:  # any pre-flight failure — fail safe to remote, don't risk local OOM
        remote = True
        cores = _MAX_CORES  # can't measure the backlog -> assume the worst case and give it headroom
        why = f"pre-flight backlog count failed ({exc!r}); defaulting to remote at cores={cores}"

    mode = "REMOTE (Fabric)" if remote else "LOCAL (runner)"
    print(f"[aemo] {why} -> running {mode}", flush=True)

    build, test = run_remote(cores) if remote else run_local()

    ok = True
    for label, (success, nodes) in (("build", build), ("test", test)):
        print(f"\n=== {mode} `dbt {label}` -> success={success} ===")
        for node, status in nodes:
            print(f"  {node}: {status}")
        ok = ok and success

    print(f"\naemo {mode} build + test {'PASSED' if ok else 'FAILED'}.")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
