"""Run the aemo dbt build + test, choosing local vs Fabric-remote by how much work is pending.

A pre-flight counts the *new* AEMO files this build would fold in — the nemweb listings minus what's
already in the archive log (``csv_archive_log.parquet`` in OneLake Files), capped per source by
``download_limit``. Then:

  * **few pending** (a quick re-run after a small model/doc tweak — barely any new files) → run dbt
    **locally** in-process on the runner. No Fabric notebook spin-up (~2-3 min) for a trivial build.
  * **many pending** (a fresh lakehouse, a real backfill, or a long gap since the last run) → ship
    ONLY the dbt logic into a throwaway Fabric Python notebook via ``RemoteRunner`` and run it there
    on Fabric compute, co-located with the lakehouse.

Local vs remote is purely *which runner we construct* — the dbt commands are identical either way.
The cutoff is ``REMOTE_THRESHOLD`` (default 50). If the pre-flight can't run (network hiccup), we
fail safe to **remote** rather than risk OOMing the 2-core runner on a big local build.

Run from the aemo project dir, after `az login`, with ONELAKE_TOKEN set (and FABRIC_TOKEN too — only
read on the remote path). External assets (dim_calendar, the AEMO CSVs) live in OneLake and are read
via source(); the calendar is generated by scripts/generate_calendar.py first. Exits non-zero if
build or test fails.
"""
import os
import sys

BUILD = ["build", "--target", "dev", "--exclude", "tag:heavy"]
TEST = ["test", "--target", "dev", "--exclude", "tag:heavy"]

# Same three nemweb listings the staging model scrapes; (url, filename LIKE filter). We only need to
# count how many listed files aren't already in the archive log — the GitHub backfill the model also
# does only fires when a source is SHORT (i.e. already a small run), so it can't turn a local-sized
# run into a remote-sized one and is safely ignored here.
_LISTINGS = {
    "daily": ("https://nemweb.com.au/Reports/Current/Daily_Reports/", "%PUBLIC_DAILY%.zip%"),
    "scada_today": ("http://nemweb.com.au/Reports/Current/Dispatch_SCADA/", "%PUBLIC_DISPATCHSCADA%"),
    "price_today": ("http://nemweb.com.au/Reports/Current/DispatchIS_Reports/", "%PUBLIC_DISPATCHIS_%.zip%"),
}


def count_pending() -> int:
    """New files (per source, capped at download_limit) not yet in the archive log."""
    import duckrun

    files_path = os.environ["FILES_PATH"].rstrip("/")
    download_limit = int(os.environ.get("download_limit", "1000"))
    storage_options = (
        {"bearer_token": os.environ["ONELAKE_TOKEN"]}
        if files_path.startswith(("abfss://", "az://")) and os.environ.get("ONELAKE_TOKEN")
        else None
    )
    # connect() over a Files root discovers 0 Delta tables and moves on; we only want its DuckDB
    # session (azure secret + httpfs) to read the log parquet and the http listings.
    conn = duckrun.connect(files_path, storage_options=storage_options, read_only=True)

    log_path = files_path + "/csv_archive_log.parquet"
    done = set()
    if conn.sql(f"SELECT count(*) FROM glob('{log_path}')").fetchone()[0] > 0:
        for (key,) in conn.sql(
            f"SELECT source_type || '::' || source_filename FROM read_parquet('{log_path}')"
        ).fetchall():
            done.add(key)

    pending = 0
    for source_type, (url, like) in _LISTINGS.items():
        rows = conn.sql(f"""
            WITH html AS (SELECT content AS h FROM read_text('{url}')),
                 lines AS (SELECT unnest(string_split(h, '<br>')) AS line FROM html)
            SELECT DISTINCT
                split_part(regexp_extract(line, 'HREF="[^"]+/([^"]+\\.zip)"', 1), '.', 1) AS filename
            FROM lines
            WHERE line LIKE '{like}'
        """).fetchall()
        new = sum(1 for (fn,) in rows if fn and f"{source_type}::{fn}" not in done)
        pending += min(new, download_limit)
    return pending


def _normalize(res):
    """(success, [(node, status), ...]) from either a dbtRunnerResult or a RemoteResult."""
    ok = bool(getattr(res, "success", False))
    nodes = []
    for r in getattr(res, "result", None) or []:
        if isinstance(r, dict):  # RemoteResult: list of {"node", "status"}
            nodes.append((r.get("node"), r.get("status")))
        else:  # dbtRunnerResult: list of RunResult
            node = getattr(getattr(r, "node", None), "name", None)
            nodes.append((node, str(getattr(r, "status", ""))))
    return ok, nodes


def run_local():
    from dbt.cli.main import dbtRunner

    dbt = dbtRunner()
    return _normalize(dbt.invoke(BUILD)), _normalize(dbt.invoke(TEST))


def run_remote():
    from duckrun import RemoteRunner

    # Batched: build then test in ONE notebook (one session start, one install). Normal released
    # duckrun from PyPI runs the project; the thing under test is RemoteRunner's orchestration.
    # cores=32: a bigger Fabric SKU brings more RAM AND a larger local disk, so DuckDB's merge spill
    # (fct_scada) has room instead of hitting the smaller notebook's ~19 GiB temp disk.
    with RemoteRunner(
        cores=32,
        target="dev",
        pip_spec="duckrun",
        fabric_token=os.environ["FABRIC_TOKEN"],
        storage_token=os.environ["ONELAKE_TOKEN"],
    ) as dbt:
        build = dbt.invoke(BUILD)
        test = dbt.invoke(TEST)
    return _normalize(build), _normalize(test)


def main() -> int:
    download_limit = int(os.environ.get("download_limit", "1000"))
    threshold = int(os.environ.get("REMOTE_THRESHOLD", "50"))
    try:
        pending = count_pending()
        remote = pending > threshold
        why = f"pending new files (capped at download_limit={download_limit}): {pending}"
    except Exception as exc:  # network/listing failure — fail safe to remote, don't risk local OOM
        pending, remote = None, True
        why = f"pre-flight count failed ({exc!r}); defaulting to remote"

    mode = "REMOTE (Fabric)" if remote else "LOCAL (runner)"
    print(f"[aemo] {why}; threshold={threshold} -> running {mode}", flush=True)

    build, test = run_remote() if remote else run_local()

    ok = True
    for label, (success, nodes) in (("build", build), ("test", test)):
        print(f"\n=== {mode} `dbt {label}` -> success={success} ===")
        for node, status in nodes:
            print(f"  {node}: {status}")
        ok = ok and success

    print(f"\naemo {mode} build + test {'PASSED' if ok else 'FAILED'}.")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
