version: 2

models:
  - name: orders_delta
    columns:
      - name: status
        tests:
          - not_null
          - unique
  - name: orders_incr
    columns:
      - name: order_id
        tests:
          - not_null
          - unique
