"""Rigorous MERGE smoke test on a big fact table — four distinct merge shapes.

Generate one big TPCH ``lineitem`` (default SF=20, ~120M rows) as the target Delta table, then
run four different incremental merges against it, in order, on the same growing table:

  1. Mixed upsert (~1% sample): ~80% existing keys with randomized measures (UPDATE) + ~20%
     key-shifted (INSERT). The everyday incremental model.
  2. Insert-only (~30M rows): a big sample, key-shifted past the max key so nothing matches, and
     stamped with a *future* l_shipdate (year 2035, well outside TPCH's 1992-1998) as a marker —
     so we can prove exactly those rows were inserted.
  3. Update-only (~5% sample): existing keys, randomized measures, NO key shift — every source
     row matches. Heaviest merge join (100% match rate); the row count must not change.
  4. Idempotent re-merge: re-run scenario 3's exact batch — a correct MERGE is idempotent, so
     nothing must change (same row count, same values).

No artificial memory cgroup: the question is whether duckrun completes all four on the runner's
real RAM, or gets OOM-killed. Data is generated by `tpchgen-cli`. The merges run with duckrun's
shipping defaults — ``preserve_insertion_order=false`` (engine.configure_duckdb_session) plus a
per-merge DuckDB ``memory_limit`` (engine.set_merge_memory_limit) and the delta_rs merge spill
cap, mirroring the dbt plugin's merge path.

    python tools/merge_tpch_bench.py --dir /tmp/m --sf 20

Each scenario materializes its source to parquet so counts are stable, then asserts the row
count moved as expected and (where relevant) the merged values landed. Exit 0 = all passed.
"""
import argparse
import glob
import os
import shutil
import subprocess
import sys
import time

import duckdb
import deltalake

from deltalake import DeltaTable

from dbt.adapters.duckrun import engine

KEYS = ["l_orderkey", "l_linenumber"]
BASE = "base"              # the target fact Delta table
SOURCE = "source.parquet"  # the materialized incremental batch (per scenario)
MIXED_INSERT_RATIO = 0.2   # of the mixed-upsert sample, the fraction that becomes INSERTs
FUTURE_SHIPDATE = "2035-06-15"  # marker date for the insert-only batch (outside TPCH's range)

# Randomized measure values for sampled rows. Replaces the four numeric measures so updated /
# inserted rows carry fresh data we can verify after the merge.
RAND_MEASURES = (
    "(random() * 50)::DECIMAL(15,2) AS l_quantity, "
    "(random() * 100000)::DECIMAL(15,2) AS l_extendedprice, "
    "(random() * 0.1)::DECIMAL(15,2) AS l_discount, "
    "(random() * 0.08)::DECIMAL(15,2) AS l_tax"
)


def _lineitem_glob(subdir):
    # tpchgen-cli writes <output-dir>/lineitem/lineitem.<k>.parquet
    return os.path.join(subdir, "lineitem", "*.parquet")


def _peak_rss_mb():
    """Best-effort peak memory in MB: Linux VmHWM, else Windows PeakWorkingSetSize; None
    if neither is available."""
    try:
        with open("/proc/self/status") as fh:
            for line in fh:
                if line.startswith("VmHWM:"):
                    return int(line.split()[1]) // 1024
    except OSError:
        pass
    try:
        import ctypes
        from ctypes import wintypes

        class _PMC(ctypes.Structure):
            _fields_ = [("cb", wintypes.DWORD), ("PageFaultCount", wintypes.DWORD)] + [
                (n, ctypes.c_size_t) for n in (
                    "PeakWorkingSetSize", "WorkingSetSize", "QuotaPeakPagedPoolUsage",
                    "QuotaPagedPoolUsage", "QuotaPeakNonPagedPoolUsage",
                    "QuotaNonPagedPoolUsage", "PagefileUsage", "PeakPagefileUsage")
            ]

        k32 = ctypes.windll.kernel32
        k32.GetCurrentProcess.restype = wintypes.HANDLE
        p = _PMC()
        p.cb = ctypes.sizeof(_PMC)
        if ctypes.windll.psapi.GetProcessMemoryInfo(k32.GetCurrentProcess(), ctypes.byref(p), p.cb):
            return p.PeakWorkingSetSize // (1024 * 1024)
    except Exception:
        pass
    return None


def _gen_target(out_dir, sf):
    """Generate lineitem at scale `sf` into out_dir/lineitem/ (one part per ~2 SF, min 1)."""
    shutil.rmtree(os.path.join(out_dir, "lineitem"), ignore_errors=True)
    os.makedirs(out_dir, exist_ok=True)
    parts = max(1, round(sf / 2))
    t = time.time()
    subprocess.run(
        ["tpchgen-cli", "-s", str(sf), "--tables", "lineitem",
         "--parts", str(parts), "--format", "parquet", "--output-dir", out_dir],
        check=True,
    )
    print(f"  generated SF={sf} lineitem ({parts} parts) in {time.time()-t:.1f}s")


def _count(base):
    return DeltaTable(base).to_pyarrow_dataset().count_rows()


def _merge(con, base, source):
    """Run the duckrun merge from a materialized source parquet; return elapsed seconds."""
    src = con.sql(f"SELECT * FROM read_parquet('{source}')")
    # Mirror the dbt plugin's merge path: tighten DuckDB to its split share right before the
    # merge (the write/build path above leaves DuckDB managing its own memory).
    engine.set_merge_memory_limit(con)
    t = time.time()
    engine.merge_delta(base, src, KEYS)
    return time.time() - t


def _verify_updates(con, base, source, cur_max):
    """Sample updated rows (existing keys, l_orderkey <= cur_max) and confirm the merge wrote
    the source's l_quantity. Returns the count of mismatches (0 = good)."""
    return con.execute(f"""
        SELECT count(*) FROM (
          SELECT l_orderkey, l_linenumber, l_quantity
          FROM read_parquet('{source}') WHERE l_orderkey <= {cur_max} LIMIT 1000
        ) s JOIN delta_scan('{base}') b USING (l_orderkey, l_linenumber)
        WHERE b.l_quantity != s.l_quantity
    """).fetchone()[0]


def _scenario_mixed(con, tgt_glob, base, source, frac):
    """~`frac` sample: most rows UPDATE (existing key, randomized measures), a slice INSERT
    (key-shifted). Expect rows += inserts; updated rows carry the new measures."""
    before = _count(base)
    cur_max = con.execute(f"SELECT max(l_orderkey) FROM delta_scan('{base}')").fetchone()[0]
    if os.path.exists(source):
        os.remove(source)
    con.execute(f"""
        COPY (
          WITH s AS (
            SELECT *, random() AS _r
            FROM read_parquet('{tgt_glob}') USING SAMPLE {frac * 100} PERCENT (bernoulli)
          )
          SELECT * EXCLUDE (_r) REPLACE ({RAND_MEASURES}) FROM s WHERE _r >= {MIXED_INSERT_RATIO}
          UNION ALL
          SELECT * EXCLUDE (_r) REPLACE (l_orderkey + {cur_max} AS l_orderkey, {RAND_MEASURES})
          FROM s WHERE _r < {MIXED_INSERT_RATIO}
        ) TO '{source}' (FORMAT parquet)
    """)
    src_rows = con.execute(f"SELECT count(*) FROM read_parquet('{source}')").fetchone()[0]
    ins = con.execute(
        f"SELECT count(*) FROM read_parquet('{source}') WHERE l_orderkey > {cur_max}").fetchone()[0]
    dt = _merge(con, base, source)
    after = _count(base)
    bad = _verify_updates(con, base, source, cur_max)
    return {
        "name": "Mixed upsert", "src": src_rows, "upd": src_rows - ins, "ins": ins,
        "before": before, "after": after, "expected": before + ins, "dt": dt,
        "count_ok": after == before + ins, "verify_ok": not bad,
        "verify": "updated rows carry new measures",
    }


def _scenario_insert_only(con, tgt_glob, base, source, frac):
    """~`frac` sample, key-shifted past the max key (so nothing matches) and stamped with a
    future l_shipdate. Expect every row INSERTed (rows += src), and exactly src rows carry the
    future date."""
    before = _count(base)
    cur_max = con.execute(f"SELECT max(l_orderkey) FROM delta_scan('{base}')").fetchone()[0]
    if os.path.exists(source):
        os.remove(source)
    con.execute(f"""
        COPY (
          SELECT * REPLACE (l_orderkey + {cur_max} AS l_orderkey, DATE '{FUTURE_SHIPDATE}' AS l_shipdate)
          FROM read_parquet('{tgt_glob}') USING SAMPLE {frac * 100} PERCENT (bernoulli)
        ) TO '{source}' (FORMAT parquet)
    """)
    src_rows = con.execute(f"SELECT count(*) FROM read_parquet('{source}')").fetchone()[0]
    dt = _merge(con, base, source)
    after = _count(base)
    future_rows = con.execute(
        f"SELECT count(*) FROM delta_scan('{base}') WHERE l_shipdate = DATE '{FUTURE_SHIPDATE}'").fetchone()[0]
    return {
        "name": "Insert-only (future shipdate)", "src": src_rows, "upd": 0, "ins": src_rows,
        "before": before, "after": after, "expected": before + src_rows, "dt": dt,
        "count_ok": after == before + src_rows, "verify_ok": future_rows == src_rows,
        "verify": f"{future_rows:,} rows carry the 2035 shipdate (== inserts)",
    }


def _scenario_update_only(con, tgt_glob, base, source, frac):
    """~`frac` sample of existing keys (no shift) with randomized measures — every row matches.
    Expect the row count UNCHANGED and the sampled rows to carry the new measures."""
    before = _count(base)
    cur_max = con.execute(f"SELECT max(l_orderkey) FROM delta_scan('{base}')").fetchone()[0]
    if os.path.exists(source):
        os.remove(source)
    con.execute(f"""
        COPY (
          SELECT * REPLACE ({RAND_MEASURES})
          FROM read_parquet('{tgt_glob}') USING SAMPLE {frac * 100} PERCENT (bernoulli)
        ) TO '{source}' (FORMAT parquet)
    """)
    src_rows = con.execute(f"SELECT count(*) FROM read_parquet('{source}')").fetchone()[0]
    dt = _merge(con, base, source)
    after = _count(base)
    bad = _verify_updates(con, base, source, cur_max)
    return {
        "name": "Update-only (100% match)", "src": src_rows, "upd": src_rows, "ins": 0,
        "before": before, "after": after, "expected": before, "dt": dt,
        "count_ok": after == before, "verify_ok": not bad,
        "verify": "updated rows carry new measures",
    }


def _scenario_idempotent(con, base, source):
    """Re-merge the *same* source the update-only scenario just left behind. A correct MERGE is
    idempotent: the rows already hold these keys and these measures, so nothing must change —
    row count identical and the values still match. Catches double-apply / duplicate bugs."""
    before = _count(base)
    cur_max = con.execute(f"SELECT max(l_orderkey) FROM delta_scan('{base}')").fetchone()[0]
    src_rows = con.execute(f"SELECT count(*) FROM read_parquet('{source}')").fetchone()[0]
    dt = _merge(con, base, source)
    after = _count(base)
    bad = _verify_updates(con, base, source, cur_max)
    return {
        "name": "Idempotent re-merge", "src": src_rows, "upd": src_rows, "ins": 0,
        "before": before, "after": after, "expected": before, "dt": dt,
        "count_ok": after == before, "verify_ok": not bad,
        "verify": "re-merging the same batch changed nothing",
    }


def _scenario_write(con, base, source, mode, before):
    """Plain duckrun write (overwrite/append) of the same batch the merges use, against the SAME
    big target table — so the card compares merge vs append vs overwrite head-to-head. A write
    only lands files (overwrite also vacuums the old ones); it never scans or joins the target,
    which is why it's far cheaper than a MERGE of the same row count. Standard result dict."""
    src_rows = con.execute(f"SELECT count(*) FROM read_parquet('{source}')").fetchone()[0]
    rel = con.sql(f"SELECT * FROM read_parquet('{source}')")
    t = time.time()
    engine.write_delta(base, rel, mode)
    dt = time.time() - t
    after = _count(base)
    expected = src_rows if mode == "overwrite" else before + src_rows
    verify = (f"overwrite replaced the table with {src_rows:,} rows (vacuumed the old {before:,})"
              if mode == "overwrite"
              else f"appended {src_rows:,} rows to the {before:,}-row table — no target scan")
    return {
        "name": f"{mode.capitalize()} (no merge)", "src": src_rows, "upd": 0, "ins": src_rows,
        "before": before, "after": after, "expected": expected, "dt": dt,
        "count_ok": after == expected, "verify_ok": True,
        "verify": verify,
    }


def run(args):
    target_dir = os.path.join(args.dir, "target")
    base = os.path.join(args.dir, BASE)
    source = os.path.join(args.dir, SOURCE)
    tgt_glob = _lineitem_glob(target_dir)

    print(f"== generate target SF={args.sf} ==")
    _gen_target(target_dir, args.sf)

    con = duckdb.connect()
    con.execute("INSTALL delta; LOAD delta;")
    # Mirror the real duckrun connection: always-on session tuning (temp_directory +
    # preserve_insertion_order=false) — the same call the dbt plugin makes. The DuckDB
    # memory_limit is left to DuckDB here (the write/build path); _merge() tightens it to the
    # split share right before each merge, exactly as the plugin's merge branch does.
    engine.configure_duckdb_session(con)
    target_rows = con.execute(f"SELECT count(*) FROM read_parquet('{tgt_glob}')").fetchone()[0]
    eff = engine._effective_mem_limit_bytes()
    dflt = engine._default_merge_spill_size()
    duckdb_mem = con.execute("SELECT current_setting('memory_limit')").fetchone()[0]
    print(f"== target: {target_rows:,} rows ==")
    print(f"   effective_mem={None if eff is None else round(eff/1048576)}MB "
          f"merge_cap={None if dflt is None else round(dflt/1048576)}MB "
          f"duckdb_memory_limit={duckdb_mem}")

    setup = {
        "duckdb_ver": duckdb.__version__,
        "deltalake_ver": deltalake.__version__,
        "sf": args.sf,
        "target_rows": target_rows,
        "eff_mb": None if eff is None else round(eff / 1048576),
        "duckdb_mem": duckdb_mem,
        "cap_mb": None if dflt is None else round(dflt / 1048576),
        "mixed_pct": f"{args.mixed_frac * 100:g}%",
        "insert_pct": f"{args.insert_frac * 100:g}%",
        "update_pct": f"{args.update_frac * 100:g}%",
    }

    # Build the target fact Delta table part-by-part. Writing all ~120M rows in one
    # write_deltalake holds the whole stream at once (no spill on the write path, unlike the
    # merge) and OOM-kills the runner; appending one parquet part at a time bounds it.
    if os.path.exists(base):
        shutil.rmtree(base)
    t = time.time()
    parts = sorted(glob.glob(os.path.join(target_dir, "lineitem", "*.parquet")))
    for i, pf in enumerate(parts):
        rel = con.sql(f"SELECT * FROM read_parquet('{pf.replace(os.sep, '/')}')")
        engine.write_delta(base, rel, "overwrite" if i == 0 else "append")
    print(f"   wrote target Delta from {len(parts)} parts "
          f"({len(DeltaTable(base).file_uris())} files) in {time.time()-t:.1f}s")

    results = [
        _scenario_mixed(con, tgt_glob, base, source, args.mixed_frac),
        _scenario_insert_only(con, tgt_glob, base, source, args.insert_frac),
        _scenario_update_only(con, tgt_glob, base, source, args.update_frac),
        # Reuses the source the update-only scenario just materialized — re-merging it must
        # be a no-op (idempotency). Keep last so that source still exists.
        _scenario_idempotent(con, base, source),
    ]
    # Same target, no MERGE: append the same batch, then overwrite — so the one card compares
    # merge vs append vs overwrite of an identical batch against the *same* big table. Kept last
    # (overwrite is destructive) and after the merge asserts above have all been captured.
    n = _count(base)
    r_append = _scenario_write(con, base, source, "append", n)
    results.append(r_append)
    results.append(_scenario_write(con, base, source, "overwrite", r_append["after"]))

    ok = True
    for r in results:
        status = "OK" if (r["count_ok"] and r["verify_ok"]) else "FAIL"
        ok = ok and r["count_ok"] and r["verify_ok"]
        print(f"== [{status}] {r['name']}: {r['src']:,} rows "
              f"({r['upd']:,} upd + {r['ins']:,} ins) in {r['dt']:.1f}s; "
              f"rows {r['before']:,} -> {r['after']:,} (expected {r['expected']:,}); "
              f"{r['verify']} ==")
        if not r["count_ok"]:
            print(f"   FAIL: row count {r['after']:,} != expected {r['expected']:,}", file=sys.stderr)
        if not r["verify_ok"]:
            print(f"   FAIL: value check failed ({r['verify']})", file=sys.stderr)

    peak = _peak_rss_mb()
    print(f"== done: peakRSS={peak}MB (target grew to {n:,} rows across the merges) ==")
    _write_summary(setup, results, n, peak, ok)
    if not ok:
        sys.exit(2)
    print("OK: duckrun ran the merges + overwrite/append on a big table correctly and survived.")


def _write_summary(setup, results, final_rows, peak, all_ok):
    """Append a data-engineer-readable report to $GITHUB_STEP_SUMMARY (no-op locally)."""
    path = os.environ.get("GITHUB_STEP_SUMMARY")
    if not path:
        return
    peak_s = f"{peak:,} MB" if peak is not None else "n/a"
    L = []
    L.append("## 🔀 Incremental MERGE test — duckrun on Delta Lake")
    L.append("")
    L.append("**What this checks:** that duckrun MERGEs incremental batches into a large Delta "
             "*fact* table on one machine — across four merge shapes — applying UPDATEs and "
             "INSERTs correctly without being OOM-killed, and how the same batch compares against "
             "a plain `append` / `overwrite` on that same table (which never scan the target).")
    L.append("")
    L.append("### Setup (the inputs)")
    L.append("| | |")
    L.append("|---|---|")
    L.append(f"| Engine | duckrun &middot; DuckDB {setup['duckdb_ver']} &middot; "
             f"delta_rs {setup['deltalake_ver']} |")
    L.append(f"| Target fact table | TPCH `lineitem`, scale factor **{setup['sf']}** → "
             f"**{setup['target_rows']:,} rows** |")
    L.append("| Primary key (merge on) | `(l_orderkey, l_linenumber)` |")
    L.append(f"| Effective memory | {setup['eff_mb']} MB (runner RAM, no artificial limit) |")
    L.append(f"| DuckDB `memory_limit` | {setup['duckdb_mem']} — set by duckrun (cgroup-aware) |")
    L.append(f"| Merge spill cap | {setup['cap_mb']} MB — delta_rs `max_spill_size` |")
    L.append("")
    L.append("### The operations (run in order, on the same growing table)")
    L.append(f"1. **Mixed upsert (~{setup['mixed_pct']} sample):** ~80% existing keys → UPDATE "
             "(randomized measures), ~20% key-shifted → INSERT. _Expect:_ rows grow by the inserts; "
             "updated rows carry the new measures.")
    L.append(f"2. **Insert-only (~{setup['insert_pct']} sample):** key-shifted past the max key so "
             "nothing matches, stamped with a future `l_shipdate` (2035). _Expect:_ every row "
             "INSERTed; exactly that many rows carry the 2035 date.")
    L.append(f"3. **Update-only (~{setup['update_pct']} sample):** existing keys, randomized "
             "measures, no key shift → 100% match. _Expect:_ row count unchanged; rows carry the "
             "new measures.")
    L.append("4. **Idempotent re-merge:** re-run scenario 3's exact batch. _Expect:_ a correct "
             "MERGE is idempotent — nothing changes (same row count, same values).")
    L.append("5. **Append (no merge):** the same batch appended to the table. _Expect:_ rows grow "
             "by the batch — and it's far faster, because an append only lands files.")
    L.append("6. **Overwrite (no merge):** the same batch overwriting the table. _Expect:_ the "
             "table is replaced by the batch — also far faster than a MERGE (no target scan/join).")
    L.append("")
    L.append("### Results")
    L.append("| Operation | Increment | Updates | Inserts | Rows before | Rows after | Expected | Count ✓ | Values ✓ | Time |")
    L.append("|---|---:|---:|---:|---:|---:|---:|:---:|:---:|---:|")
    for r in results:
        L.append(
            f"| {r['name']} | {r['src']:,} | {r['upd']:,} | {r['ins']:,} | {r['before']:,} | "
            f"{r['after']:,} | {r['expected']:,} | {'✅' if r['count_ok'] else '❌'} | "
            f"{'✅' if r['verify_ok'] else '❌'} | {r['dt']:.1f}s |")
    L.append("")
    L.append("_The last two rows are the same batch as a plain append / overwrite — compare their "
             "time against the merges above to see the cost a MERGE pays to scan & join the target._")
    L.append("")
    verdict = (f"**Result: ✅ all operations correct.** Target grew to **{final_rows:,} rows** across "
               f"the merges, peak memory **{peak_s}** — duckrun stayed within the runner's RAM and "
               f"every update/insert landed as expected."
               if all_ok else
               "**Result: ❌ one or more operations were wrong** — see the ❌ cells above and the step log.")
    L.append(verdict)
    with open(path, "a", encoding="utf-8") as fh:
        fh.write("\n".join(L) + "\n")


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--dir", required=True)
    ap.add_argument("--sf", type=float, default=20.0, help="target fact table scale factor")
    ap.add_argument("--mixed-frac", type=float, default=0.01, dest="mixed_frac",
                    help="sample fraction for the mixed upsert scenario")
    ap.add_argument("--insert-frac", type=float, default=0.05, dest="insert_frac",
                    help="sample fraction for the insert-only scenario (a realistic incremental "
                         "delta, ~3M rows at SF=10; not a 25%-of-table bulk load)")
    ap.add_argument("--update-frac", type=float, default=0.05, dest="update_frac",
                    help="sample fraction for the update-only scenario")
    ap.set_defaults(func=run)
    args = ap.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
