"""Rigorous incremental-MERGE smoke test on a big fact table.

Take a small (~0.1%) sample of the fact table, **randomize its measure values**, and merge it
back in — repeated **three times** to simulate successive incremental loads. TPCH ``lineitem``
is the fact table, and we cover the full MERGE path: most of each increment matches existing
keys (UPDATE, randomized measures) and a slice is key-shifted past the max key so it does not
match (INSERT).

No artificial memory cgroup: the question is whether duckrun completes three real merges into a
big table on the runner's actual RAM, or gets OOM-killed. Data is generated by `tpchgen-cli`.
The merge runs with duckrun's shipping defaults — the cgroup-aware DuckDB ``memory_limit``
(engine.configure_duckdb_memory, mirroring the dbt plugin at connection-open) and the delta_rs
merge ``max_spill_size``.

    python tools/merge_tpch_bench.py --dir /tmp/m --sf 20 --sample-frac 0.001 --rounds 3

Each round materializes its source to parquet so insert/update counts are stable, then checks:
the row count grew by exactly the inserts, and the updated rows carry the source's randomized
measures. Exit 0 = all rounds completed and matched.
"""
import argparse
import glob
import os
import shutil
import subprocess
import sys
import time

import duckdb
import deltalake

from deltalake import DeltaTable

from dbt.adapters.duckrun import engine

KEYS = ["l_orderkey", "l_linenumber"]
BASE = "base"              # the target fact Delta table
SOURCE = "source.parquet"  # the materialized incremental batch (per round)

# Randomized measure values for the sampled rows — the "randomize values" step. Replaces the
# four numeric measures so both UPDATE (existing keys) and INSERT (shifted keys) carry fresh
# data we can verify after the merge.
RAND_MEASURES = (
    "(random() * 50)::DECIMAL(15,2) AS l_quantity, "
    "(random() * 100000)::DECIMAL(15,2) AS l_extendedprice, "
    "(random() * 0.1)::DECIMAL(15,2) AS l_discount, "
    "(random() * 0.08)::DECIMAL(15,2) AS l_tax"
)


def _lineitem_glob(subdir):
    # tpchgen-cli writes <output-dir>/lineitem/lineitem.<k>.parquet
    return os.path.join(subdir, "lineitem", "*.parquet")


def _peak_rss_mb():
    """Best-effort peak memory in MB: Linux VmHWM, else Windows PeakWorkingSetSize; None
    if neither is available."""
    try:
        with open("/proc/self/status") as fh:
            for line in fh:
                if line.startswith("VmHWM:"):
                    return int(line.split()[1]) // 1024
    except OSError:
        pass
    try:
        import ctypes
        from ctypes import wintypes

        class _PMC(ctypes.Structure):
            _fields_ = [("cb", wintypes.DWORD), ("PageFaultCount", wintypes.DWORD)] + [
                (n, ctypes.c_size_t) for n in (
                    "PeakWorkingSetSize", "WorkingSetSize", "QuotaPeakPagedPoolUsage",
                    "QuotaPagedPoolUsage", "QuotaPeakNonPagedPoolUsage",
                    "QuotaNonPagedPoolUsage", "PagefileUsage", "PeakPagefileUsage")
            ]

        k32 = ctypes.windll.kernel32
        k32.GetCurrentProcess.restype = wintypes.HANDLE
        p = _PMC()
        p.cb = ctypes.sizeof(_PMC)
        if ctypes.windll.psapi.GetProcessMemoryInfo(k32.GetCurrentProcess(), ctypes.byref(p), p.cb):
            return p.PeakWorkingSetSize // (1024 * 1024)
    except Exception:
        pass
    return None


def _gen_target(out_dir, sf):
    """Generate lineitem at scale `sf` into out_dir/lineitem/ (one part per ~2 SF, min 1)."""
    shutil.rmtree(os.path.join(out_dir, "lineitem"), ignore_errors=True)
    os.makedirs(out_dir, exist_ok=True)
    parts = max(1, round(sf / 2))
    t = time.time()
    subprocess.run(
        ["tpchgen-cli", "-s", str(sf), "--tables", "lineitem",
         "--parts", str(parts), "--format", "parquet", "--output-dir", out_dir],
        check=True,
    )
    print(f"  generated SF={sf} lineitem ({parts} parts) in {time.time()-t:.1f}s")


def _write_summary(setup, rounds_data, final_rows, peak, all_ok):
    """Append a data-engineer-readable report to $GITHUB_STEP_SUMMARY (no-op locally)."""
    path = os.environ.get("GITHUB_STEP_SUMMARY")
    if not path:
        return
    peak_s = f"{peak:,} MB" if peak is not None else "n/a"
    L = []
    L.append("## 🔀 Incremental MERGE test — duckrun on Delta Lake")
    L.append("")
    L.append("**What this checks:** that duckrun can repeatedly MERGE small incremental batches "
             "into a large Delta *fact* table on one machine — applying UPDATEs and INSERTs "
             "correctly — without being OOM-killed. This is the everyday `incremental` dbt model "
             "pattern, at scale.")
    L.append("")
    L.append("### Setup (the inputs)")
    L.append("| | |")
    L.append("|---|---|")
    L.append(f"| Engine | duckrun &middot; DuckDB {setup['duckdb_ver']} &middot; "
             f"delta_rs {setup['deltalake_ver']} |")
    L.append(f"| Target fact table | TPCH `lineitem`, scale factor **{setup['sf']}** → "
             f"**{setup['target_rows']:,} rows** |")
    L.append("| Primary key (merge on) | `(l_orderkey, l_linenumber)` |")
    L.append(f"| Effective memory | {setup['eff_mb']} MB (runner RAM, no artificial limit) |")
    L.append(f"| DuckDB `memory_limit` | {setup['duckdb_mem']} — set by duckrun (cgroup-aware) |")
    L.append(f"| Merge spill cap | {setup['cap_mb']} MB — delta_rs `max_spill_size`, spills to disk above this |")
    L.append(f"| Increment per round | ~{setup['sample_pct']} of the fact, **measure columns randomized** |")
    L.append(f"| Rounds | **{setup['rounds']}** successive incremental loads |")
    L.append("")
    L.append("### What each round does")
    L.append("- **Input:** a fresh random ~" + setup['sample_pct'] + " sample of the fact table. "
             "Most rows keep their key → **UPDATE** (same `(l_orderkey, l_linenumber)`, new "
             "randomized `l_quantity` / `l_extendedprice` / `l_discount` / `l_tax`). A slice has "
             "its `l_orderkey` shifted beyond the current max key → **INSERT** (brand-new rows).")
    L.append("- **Expected output:** after the merge the row count rises by **exactly the number "
             "of inserts** (updates never change the count), and every updated row now carries "
             "the source's new randomized `l_quantity`.")
    L.append("")
    L.append("### Results")
    L.append("| Round | Increment | Updates | Inserts | Rows before | Rows after | Expected after | Count ✓ | Updates ✓ | Time |")
    L.append("|------:|----------:|--------:|--------:|------------:|-----------:|---------------:|:-------:|:---------:|-----:|")
    for r in rounds_data:
        L.append(
            f"| {r['round']} | {r['src']:,} | {r['upd']:,} | {r['ins']:,} | {r['before']:,} | "
            f"{r['after']:,} | {r['expected']:,} | {'✅' if r['count_ok'] else '❌'} | "
            f"{'✅' if r['upd_ok'] else '❌'} | {r['dt']:.1f}s |")
    L.append("")
    verdict = (f"**Result: ✅ all {len(rounds_data)} rounds correct.** Final table "
               f"**{final_rows:,} rows**, peak memory **{peak_s}** — duckrun stayed within the "
               f"runner's RAM and every update/insert landed as expected."
               if all_ok else
               "**Result: ❌ one or more rounds were wrong** — see the ❌ cells above and the step log.")
    L.append(verdict)
    L.append("")
    L.append("> _Count ✓_ = row count grew by exactly the inserts. _Updates ✓_ = sampled updated "
             "rows carry the source's randomized measures (the MERGE actually rewrote them).")
    with open(path, "a", encoding="utf-8") as fh:
        fh.write("\n".join(L) + "\n")


def _build_source(con, tgt_glob, source, sample_frac, insert_ratio, key_shift):
    """Materialize one round's increment: a `sample_frac` bernoulli sample of the target with
    randomized measures; an `insert_ratio` slice of it gets its l_orderkey shifted by `key_shift`
    (> any existing key) to become INSERTs, the rest stay matched UPDATEs."""
    if os.path.exists(source):
        os.remove(source)
    con.execute(f"""
        COPY (
          WITH s AS (
            SELECT *, random() AS _r
            FROM read_parquet('{tgt_glob}') USING SAMPLE {sample_frac * 100} PERCENT (bernoulli)
          )
          SELECT * EXCLUDE (_r) REPLACE ({RAND_MEASURES})
          FROM s WHERE _r >= {insert_ratio}
          UNION ALL
          SELECT * EXCLUDE (_r) REPLACE (l_orderkey + {key_shift} AS l_orderkey, {RAND_MEASURES})
          FROM s WHERE _r < {insert_ratio}
        ) TO '{source}' (FORMAT parquet)
    """)


def run(args):
    target_dir = os.path.join(args.dir, "target")
    base = os.path.join(args.dir, BASE)
    source = os.path.join(args.dir, SOURCE)
    tgt_glob = _lineitem_glob(target_dir)

    print(f"== generate target SF={args.sf} ==")
    _gen_target(target_dir, args.sf)

    con = duckdb.connect()
    con.execute("INSTALL delta; LOAD delta;")
    # Mirror the real duckrun connection: duckrun's session tuning (cgroup-aware memory_limit +
    # temp_directory + preserve_insertion_order=false) — the same call the dbt plugin makes.
    engine.configure_duckdb_memory(con)
    target_rows = con.execute(f"SELECT count(*) FROM read_parquet('{tgt_glob}')").fetchone()[0]
    eff = engine._effective_mem_limit_bytes()
    dflt = engine._default_merge_spill_size()
    duckdb_mem = con.execute("SELECT current_setting('memory_limit')").fetchone()[0]
    print(f"== target: {target_rows:,} rows ==")
    print(f"   effective_mem={None if eff is None else round(eff/1048576)}MB "
          f"merge_cap={None if dflt is None else round(dflt/1048576)}MB "
          f"duckdb_memory_limit={duckdb_mem}")

    setup = {
        "duckdb_ver": duckdb.__version__,
        "deltalake_ver": deltalake.__version__,
        "sf": args.sf,
        "target_rows": target_rows,
        "eff_mb": None if eff is None else round(eff / 1048576),
        "duckdb_mem": duckdb_mem,
        "cap_mb": None if dflt is None else round(dflt / 1048576),
        "sample_pct": f"{args.sample_frac * 100:g}%",
        "rounds": args.rounds,
    }

    # Build the target fact Delta table part-by-part. Writing all ~120M rows in one
    # write_deltalake holds the whole stream at once (no spill on the write path, unlike the
    # merge) and OOM-kills the runner; appending one parquet part at a time bounds it.
    if os.path.exists(base):
        shutil.rmtree(base)
    t = time.time()
    parts = sorted(glob.glob(os.path.join(target_dir, "lineitem", "*.parquet")))
    for i, pf in enumerate(parts):
        rel = con.sql(f"SELECT * FROM read_parquet('{pf.replace(os.sep, '/')}')")
        engine.write_delta(base, rel, "overwrite" if i == 0 else "append")
    print(f"   wrote target Delta from {len(parts)} parts "
          f"({len(DeltaTable(base).file_uris())} files) in {time.time()-t:.1f}s")

    ok = True
    rounds_data = []
    for rnd in range(1, args.rounds + 1):
        before = DeltaTable(base).to_pyarrow_dataset().count_rows()
        cur_max = con.execute(f"SELECT max(l_orderkey) FROM delta_scan('{base}')").fetchone()[0]
        _build_source(con, tgt_glob, source, args.sample_frac, args.insert_ratio, cur_max)
        src_rows = con.execute(f"SELECT count(*) FROM read_parquet('{source}')").fetchone()[0]
        ins_rows = con.execute(
            f"SELECT count(*) FROM read_parquet('{source}') WHERE l_orderkey > {cur_max}").fetchone()[0]
        upd_rows = src_rows - ins_rows

        src = con.sql(f"SELECT * FROM read_parquet('{source}')")
        t = time.time()
        engine.merge_delta(base, src, KEYS)
        dt = time.time() - t
        after = DeltaTable(base).to_pyarrow_dataset().count_rows()
        print(f"== round {rnd}/{args.rounds}: merged {src_rows:,} "
              f"({upd_rows:,} upd + {ins_rows:,} ins) in {dt:.1f}s; "
              f"rows {before:,} -> {after:,} (expected {before + ins_rows:,}) ==")

        count_ok = after == before + ins_rows
        if not count_ok:
            print(f"FAIL round {rnd}: row count {after:,} != {before:,} + inserts {ins_rows:,}",
                  file=sys.stderr)
        bad = con.execute(f"""
            SELECT count(*) FROM (
              SELECT l_orderkey, l_linenumber, l_quantity
              FROM read_parquet('{source}') WHERE l_orderkey <= {cur_max} LIMIT 1000
            ) s JOIN delta_scan('{base}') b USING (l_orderkey, l_linenumber)
            WHERE b.l_quantity != s.l_quantity
        """).fetchone()[0]
        if bad:
            print(f"FAIL round {rnd}: {bad} sampled updated rows did not carry the source measures",
                  file=sys.stderr)
        ok = ok and count_ok and not bad
        rounds_data.append({
            "round": rnd, "src": src_rows, "upd": upd_rows, "ins": ins_rows,
            "before": before, "after": after, "expected": before + ins_rows,
            "count_ok": count_ok, "upd_ok": not bad, "dt": dt,
        })

    peak = _peak_rss_mb()
    final = DeltaTable(base).to_pyarrow_dataset().count_rows()
    print(f"== {args.rounds} rounds done: final rows={final:,} (from {target_rows:,}) "
          f"peakRSS={peak}MB ==")
    _write_summary(setup, rounds_data, final, peak, ok)
    if not ok:
        sys.exit(2)
    print(f"OK: duckrun ran {args.rounds} incremental merges (update + insert) into a "
          f"{target_rows:,}-row table correctly and survived.")


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--dir", required=True)
    ap.add_argument("--sf", type=float, default=20.0, help="target fact table scale factor")
    ap.add_argument("--sample-frac", type=float, default=0.001, dest="sample_frac",
                    help="fraction of the fact table sampled per round (default 0.1%%)")
    ap.add_argument("--insert-ratio", type=float, default=0.2, dest="insert_ratio",
                    help="fraction of each increment that is INSERTs (rest are UPDATEs)")
    ap.add_argument("--rounds", type=int, default=3, help="number of sequential incremental merges")
    ap.set_defaults(func=run)
    args = ap.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
